CREATE SCHEMA IF NOT EXISTS kzn;

CREATE TABLE IF NOT EXISTS kzn.users (
id SERIAL PRIMARY KEY,
login VARCHAR(255) NOT NULL UNIQUE,
    created_at DATE NOT NULL
    );

GRANT ALL PRIVILEGES ON SCHEMA kzn TO admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA kzn TO admin;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA kzn TO admin;