version: '3.8'

services:
  postgres:
    build: ./docker/postgres
    container_name: user-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret

volumes:
  postgres_data: